package db

import (
	"context"
)

type Store interface {
	// UserQuerier
	// other queriers
	// TransferTx(ctx context.Context, arg TransferTxParams) (TransferTxResult, error)
	CreateUser(ctx context.Context, user *User) error
}

type SQLStore struct {
	// *Queries // sql statements generated by sqlc
	// db *sql.DB
}

func NewStore() Store {
	return &SQLStore{
		// Queries: New(db),
		// db: db,
	}
}

func (s *SQLStore) CreateUser(ctx context.Context, user *User) error {
	// return s.Queries.CreateUser(ctx, user)
	
	return nil
}